image:
  repository: ghcr.io/veriload/veriload-operator
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: veriload-operator
namespaceOverride: veriload-system

replicaCount: 1

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

podAnnotations: {}
podLabels: {}

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
imagePullSecrets: []
